name: Mandyville Modelling CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Run tests with coverage
      run: sbt clean coverage test
    - name: Coverage report
      run: sbt coverageReport
    - name: Format check
      run: sbt scalafmtCheck test:scalafmtCheck
    - uses: act10ns/slack@v1
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
